Repository Do-Farming/Do-Farming_Back, pull requests merged in 2024-07, with the labels that each got.

#15 feat: 챌린지 방 상세 조회
  src/main/java/com/hana/api/group/controller/GroupController.java
  src/main/java/com/hana/api/group/dto/GroupResponseDto.java
  src/main/java/com/hana/api/group/entity/Group.java
  src/main/java/com/hana/api/group/service/GroupService.java
  src/main/java/com/hana/api/groupMember/entity/GroupMember.java
  src/main/java/com/hana/common/config/SwaggerConfig.java
Labels: enhancement

#19 feat: 챌린지 방 삭제
  src/main/java/com/hana/api/group/controller/GroupController.java
  src/main/java/com/hana/api/group/dto/GroupRequestDto.java
  src/main/java/com/hana/api/group/service/GroupService.java
  src/main/java/com/hana/common/config/BaseResponseStatus.java
Labels: enhancement

#20 feat: 챌린지 방 전체 조회시 공개된 방만 조회
  src/main/java/com/hana/api/group/repository/GroupRepository.java
  src/main/java/com/hana/api/group/service/GroupService.java
Labels: bug, enhancement

#22 Feat: 어플리케이션 내 LLM기능 개발
  build.gradle
  src/main/java/com/hana/api/gpt/controller/GptController.java
  src/main/java/com/hana/api/gpt/service/OpenAiService.java
Labels: enhancement

#26 feat: 채팅기능 redis통한 구현, 같은질문 캐싱하여 api리소스 절약
  src/main/java/com/hana/api/gpt/controller/GptController.java
  src/main/java/com/hana/api/gpt/service/OpenAiService.java
  src/main/java/com/hana/api/group/repository/GroupRepository.java
  src/main/java/com/hana/common/config/RedisConfig.java
Labels: enhancement

#28 feat: 챌린지 모집 후 차주 월요일에 자동 챌린지 trigger 스케쥴링
  src/main/java/com/hana/DofarmingApplication.java
  src/main/java/com/hana/api/group/entity/Group.java
  src/main/java/com/hana/api/group/service/GroupService.java
  src/main/java/com/hana/common/scheduler/DynamicSchedulerService.java
  src/main/java/com/hana/common/scheduler/TaskSchedulerConfig.java
Labels: enhancement

#34 feat: 챗봇, 이미지 생성 서비스 개발
  build.gradle
  src/main/java/com/hana/api/auth/dto/CustomerUserInfoDto.java
  src/main/java/com/hana/api/auth/filter/CustomerAuthenticationFilter.java
  src/main/java/com/hana/api/gpt/controller/GptController.java
  src/main/java/com/hana/api/gpt/service/OpenAiService.java
Labels: enhancement

#36 refactor: dall-e-3
  src/main/java/com/hana/api/gpt/controller/GptController.java
  src/main/java/com/hana/api/gpt/service/OpenAiService.java
Labels: enhancement

#42 feat: 오늘의 기상미션 사물 랜덤 배정
  src/main/java/com/hana/api/challenge/entity/QuizChallenge.java
  src/main/java/com/hana/api/challenge/wakeup/controller/WakeupController.java
  src/main/java/com/hana/api/challenge/wakeup/dto/WakeupResponseDto.java
  src/main/java/com/hana/api/challenge/wakeup/entity/WakeupChallenge.java
  src/main/java/com/hana/api/challenge/wakeup/repository/WakeupChallengeRepository.java
  src/main/java/com/hana/api/challenge/wakeup/service/WakeupChallengeService.java
  src/main/java/com/hana/api/group/entity/Group.java
  src/main/java/com/hana/api/quiz/entity/Answer.java
  src/main/java/com/hana/api/user/entity/User.java
  src/main/java/com/hana/api/worldcup/entity/Worldcup.java
Labels: enhancement

#45 feat: 상품 시작날짜, 만기 날짜 설정
  src/main/java/com/hana/api/group/entity/Group.java
  src/main/java/com/hana/common/scheduler/DynamicSchedulerService.java
Labels: enhancement

#51 fix: 한 사용자는 하나의 챌린징 상품에만 가입 가능
  src/main/java/com/hana/api/group/controller/GroupController.java
  src/main/java/com/hana/api/group/service/GroupService.java
  src/main/java/com/hana/api/groupMember/repository/GroupMemberRepository.java
  src/main/java/com/hana/common/config/BaseResponseStatus.java
Labels: bug, enhancement

#52 fix: 한 사용자는 하나의 챌린징 모집글만 생성 가능
  src/main/java/com/hana/api/group/service/GroupService.java
Labels: bug, enhancement

#53 feat: 기상미션 기상 인증 Redis 저장
  build.gradle
  src/main/java/com/hana/api/challenge/wakeup/controller/WakeupController.java
  src/main/java/com/hana/api/challenge/wakeup/dto/WakeupResponseDto.java
  src/main/java/com/hana/api/challenge/wakeup/service/WakeupChallengeService.java
  src/main/java/com/hana/common/config/JacksonConfig.java
  src/main/java/com/hana/common/config/RedisConfig.java
Labels: enhancement

#55 fix: 사용자가 챌린징 중이 아닐경우
  src/main/java/com/hana/api/challenge/wakeup/service/WakeupChallengeService.java
Labels: bug

#59 feat: 특정 그룹의 사용자 기상 시간 리스트 레디스 조회
  src/main/java/com/hana/api/challenge/wakeup/controller/WakeupController.java
  src/main/java/com/hana/api/challenge/wakeup/service/WakeupChallengeService.java
  src/main/java/com/hana/api/groupMember/repository/GroupMemberRepository.java
Labels: enhancement

#63 fix: 계좌 생성 버그 픽스
  src/main/java/com/hana/api/account/controller/AccountController.java
Labels: bug

#68 feat: 취향 이상형 월드컵 항목 조회, 우승 취향과 관련된 카드 추천
  src/main/java/com/hana/api/card/entity/Card.java
  src/main/java/com/hana/api/card/repository/CardRepository.java
  src/main/java/com/hana/api/card/service/CardService.java
  src/main/java/com/hana/api/taste/controller/TasteController.java
  src/main/java/com/hana/api/taste/dto/TasteResponseDto.java
  src/main/java/com/hana/api/taste/entity/FirstRank.java
  src/main/java/com/hana/api/taste/entity/Taste.java
  src/main/java/com/hana/api/taste/repository/TasteRepository.java
  src/main/java/com/hana/api/taste/service/TasteService.java
Labels: enhancement

#69 feat: 입출금 상품 저장
  src/main/java/com/hana/api/depositsProduct/controller/DepositsProductController.java
  src/main/java/com/hana/api/depositsProduct/dto/CheckingRequest.java
  src/main/java/com/hana/api/depositsProduct/entity/DepositsType.java
  src/main/java/com/hana/api/depositsProduct/service/DepositsProductService.java
Labels: enhancement

#70 feat: 입출금 상품 조회
  src/main/java/com/hana/api/depositsProduct/controller/DepositsProductController.java
  src/main/java/com/hana/api/depositsProduct/repository/DepositsProductRepository.java
  src/main/java/com/hana/api/depositsProduct/service/DepositsProductService.java
Labels: enhancement

#74 feat: 두파밍 상품 가입
  src/main/java/com/hana/api/account/service/AccountService.java
  src/main/java/com/hana/api/depositsProduct/entity/DepositsType.java
  src/main/java/com/hana/api/signSaving/controller/SignSavingController.java
  src/main/java/com/hana/api/signSaving/dto/request/DofarmingJoinRequestDto.java
  src/main/java/com/hana/api/signSaving/service/SignSavingService.java
Labels: enhancement

#76 feat: 만보계 챌린지 웹소켓을 사용하도록 변경
  build.gradle
  src/main/java/com/hana/api/challenge/controller/WalkChallengeController.java
  src/main/java/com/hana/api/challenge/dto/response/PedometerResponse.java
  src/main/java/com/hana/api/challenge/service/WalkChallengeService.java
  src/main/java/com/hana/api/challenge/websocket/PedometerWebSocketHandler.java
  src/main/java/com/hana/common/config/WebSocketConfig.java
Labels: enhancement

#77 feat: 나의 입출금 통장 조회
  src/main/java/com/hana/api/account/controller/AccountController.java
  src/main/java/com/hana/api/account/entity/Account.java
  src/main/java/com/hana/api/account/service/AccountService.java
Labels: enhancement

#78 fix: 두파밍 상품 가입 금액 변경
  src/main/java/com/hana/api/signSaving/dto/request/DofarmingJoinRequestDto.java
  src/main/java/com/hana/api/signSaving/service/SignSavingService.java
Labels: enhancement

#81 fix: dailyRank 로직 정상동작하도록 버그 수정
  src/main/java/com/hana/api/challenge/service/WalkChallengeService.java
  src/main/java/com/hana/api/dailyRank/repository/DailyRankRepository.java
  src/main/java/com/hana/api/dailyRank/service/DailyRankService.java
Labels: enhancement

#84 feat: COOL SMS 추가 및 회원가입시 deviceId 추가
  build.gradle
  src/main/java/com/hana/api/sms/controller/SmsController.java
  src/main/java/com/hana/api/sms/dto/ReserveSmsDto.java
  src/main/java/com/hana/api/sms/dto/SmsPhoneNumberDto.java
  src/main/java/com/hana/api/sms/entity/SmsReservation.java
  src/main/java/com/hana/api/sms/repository/SmsReservationRepository.java
  src/main/java/com/hana/api/sms/service/SmsService.java
  src/main/java/com/hana/api/user/dto/request/SignUpRequest.java
  src/main/java/com/hana/api/user/entity/User.java
Labels: enhancement

#87 feat: 전체 상품 타입별 조회
  src/main/java/com/hana/api/depositsProduct/controller/DepositsProductController.java
  src/main/java/com/hana/api/depositsProduct/dto/response/DepositProductsResponse.java
  src/main/java/com/hana/api/depositsProduct/repository/DepositsProductRepository.java
  src/main/java/com/hana/api/depositsProduct/service/DepositsProductService.java
Labels: enhancement

#89 fix: 거래내역조회 DTO, 계좌 이체 Controller
  src/main/java/com/hana/api/account/controller/AccountController.java
  src/main/java/com/hana/api/account/dto/MakeTransactionDto.java
Labels: bug

#92 feat: 일별 순위 history 조회 추가
  src/main/java/com/hana/api/account/dto/MakeTransactionDto.java
  src/main/java/com/hana/api/challenge/repository/ChallengeRecordRepository.java
  src/main/java/com/hana/api/dailyRank/controller/DailyRankController.java
  src/main/java/com/hana/api/dailyRank/dto/DailyRankHistoryResponseDto.java
  src/main/java/com/hana/api/dailyRank/entity/DailyRankHistory.java
  src/main/java/com/hana/api/dailyRank/repository/DailyRankHistoryRepository.java
  src/main/java/com/hana/api/dailyRank/service/DailyRankService.java
Labels: enhancement

#97 feat: 챌린징 db 저장
  src/main/java/com/hana/api/challenge/wakeup/service/WakeupChallengeService.java
Labels: enhancement

#98 feat: 내가 속한 그룹 정보 API
  src/main/java/com/hana/api/group/controller/GroupController.java
  src/main/java/com/hana/api/group/repository/GroupRepository.java
  src/main/java/com/hana/api/groupMember/repository/GroupMemberRepository.java
  src/main/java/com/hana/api/groupMember/service/GroupMemberService.java
  src/main/java/com/hana/api/user/controller/UserController.java
  src/main/java/com/hana/api/user/service/UserService.java
Labels: enhancement

#99 feat: 퀴즈 db 저장
  src/main/java/com/hana/api/challenge/service/QuizChallengeService.java
Labels: enhancement

#103 fix: 전체 상품 조회 whitelist에 추가
  src/main/java/com/hana/api/auth/filter/CustomerAuthenticationFilter.java
Labels: bug

#105 feat: 사용자마다 랜덤 프로필 이미지 지정
  src/main/java/com/hana/api/user/dto/request/SignUpRequest.java
  src/main/java/com/hana/api/user/dto/response/MyInfoResponse.java
  src/main/java/com/hana/api/user/entity/User.java
Labels: enhancement

#107 feat: 챌린지 그룹 멤버 조회시 이미지도 조회
  src/main/java/com/hana/api/group/dto/GroupResponseDto.java
Labels: enhancement
